#!/bin/sh
set -eu



export NGINX_SERVER_NAME="${NGINX_SERVER_NAME:-_}"
export NGINX_RATE_LIMIT_APP="${NGINX_RATE_LIMIT_APP:-10r/s}"
export NGINX_RATE_LIMIT_STATIC="${NGINX_RATE_LIMIT_STATIC:-100r/s}"
export NGINX_RATE_BURST_APP="${NGINX_RATE_BURST_APP:-20}"
export NGINX_RATE_BURST_STATIC="${NGINX_RATE_BURST_STATIC:-200}"
export NGINX_CLIENT_MAX_BODY_SIZE="${NGINX_CLIENT_MAX_BODY_SIZE:-1m}"

envsubst '${NGINX_SERVER_NAME}
  ${NGINX_RATE_LIMIT_APP}
  ${NGINX_RATE_LIMIT_STATIC}
  ${NGINX_RATE_BURST_APP}
  ${NGINX_RATE_BURST_STATIC}
  ${NGINX_CLIENT_MAX_BODY_SIZE}' \
  < /etc/nginx/templates/app.conf.template \
  > /etc/nginx/conf.d/app.conf

nginx -t

exec "$@"
